# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build App And Run Unit Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_run_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal
